project:
  name: code-sentinel
  version: 0.1.0

extractors:
  python:
    enabled: true
    max_file_size: 10485760  # 10MB
    exclude_patterns:
      - "**/*.pyc"
      - "**/__pycache__/*"
      - "**/venv/*"
      - "**/.git/*"

query:
  max_results: 1000
  timeout_seconds: 300
  cache_enabled: true
  cache_dir: "${env:HOME}/.code-sentinel/cache"

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "${env:HOME}/.code-sentinel/logs/code-sentinel.log"

database:
  type: sqlite
  path: "${env:HOME}/.code-sentinel/db/code-sentinel.db"
  pool_size: 5
  max_overflow: 10

cli:
  default_command: analyze
  color_output: true
  progress_bar: true
