---
# Default configuration for Code Sentinel

# Analysis settings
analysis:
  timeout: 30  # Default timeout in seconds
  cache_enabled: true
  generate_fixes: true

# Check categories
checks:
  # Mojo-specific checks
  mojo:
    enabled: true
    severity: high
    checks:
      # AST-based checks
      unsafe_functions:
        enabled: true
        severity: high
        functions:
          - shell_execute
          - eval
          - exec
          - system
      memory_management:
        enabled: true
        severity: high
        required_patterns:
          - owned
          - borrowed
          - inout
          - memcpy
          - memset_zero
      resource_management:
        enabled: true
        severity: high
        track_resources:
          - file_handles
          - memory_allocations
          - network_connections
      ownership_model:
        enabled: true
        severity: high
        enforce_annotations: true

      # Regex-based checks
      struct_naming:
        enabled: true
        severity: medium
        pattern: "^[A-Z][a-zA-Z0-9]*$"
      fn_naming:
        enabled: true
        severity: medium
        pattern: "^[a-z][a-z0-9_]*$"
      type_hints:
        enabled: true
        severity: high

  # General security checks
  security:
    enabled: true
    severity: high
    checks:
      - sql_injection
      - xss
      - command_injection
      - path_traversal

  # Code quality checks
  quality:
    enabled: true
    severity: medium
    checks:
      - code_complexity
      - dead_code
      - duplicate_code
      - naming_conventions

  # Style checks
  style:
    enabled: true
    severity: low
    checks:
      - line_length
      - whitespace
      - documentation
      - imports

# Language-specific settings
languages:
  mojo:
    file_extensions: ['.mojo', '.🔥']
    max_line_length: 100
    indent_size: 4
    naming_conventions:
      struct: PascalCase
      function: snake_case
      variable: snake_case
      constant: SCREAMING_SNAKE_CASE
    ast_analysis:
      parser: native  # or 'python_bridge'
      cache_asts: true
      max_ast_cache_size_mb: 100
      analysis_timeout_ms: 5000

# Reporting settings
reporting:
  formats:
    - text
    - json
  include_snippets: true
  max_suggestions: 3

# Cache settings
cache:
  enabled: true
  directory: ".code-sentinel-cache"
  max_size_mb: 100
  ttl_hours: 24
